### ISSUE TITLE
Collaboration opportunity

### ISSUE THREAD

**Issue by dimitreOliveira** [deep-diver/textual-inversion-sd#1]
Hey there Chansung, I just noticed this repository that you created, for the past few days I was working on something that is quite similar to this, [here is my repository](https://github.com/dimitreOliveira/stable-diffusion-textual-inversion-app), I am not sure if you want to build your version of the code, or build it in a specific way. But let me know if you would like to collaborate, maybe we could keep just a single repository and build all the features, I have done a few things already and wrote a to-do list with my plan of the roadmap but I am very flexible on that.

**Comment by deep-diver** [comment]
Hi @dimitreOliveira 

Thank you for reaching out! 

I created this repository to demonstrate a simple TFX workflow to push fine-tuned Stable Diffusion to Hugging Face Model and Gradio application to Hugging Face Space. I will have only four or less TFX components (`Trainer` and `HFPusher` at minimum).
- All the codes from the Keras example is laid out as scripts already.

Then the Graio application would have a "deploy" button to deploy trained `text_encoder` to GCP environment(Vertex AI or GKE). Optionally, the entire Stable Diffusion will could be deployed too. 
- I noticed your repository tries to cover almost everything up (training to deployment). However, in my case, I will leverage my sibling project ["Various ways of serving Stable Diffusion"](https://github.com/deep-diver/keras-sd-serving) for the deployment purpose. 

I think there are some overlapping concepts between this repo and yours, but I think the end goal of the two are different. Please let me know what you think.

**Comment by dimitreOliveira** [comment]
Oh ok, you are probably right, from the current initial steps they both looked very similar, but as you said the end goal seems a bit different.

Thanks @deep-diver , maybe we could collaborate with something else in the future, good luck!
